# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Main Unix

on:
  push:
    branches:
      - master
      - 'rel/*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
      - 'rel/*'
      - cluster_new
    paths-ignore:
      - 'docs/**'

jobs:
  unix:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [8, 11.0.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Check Apache Rat
        run: mvn -B apache-rat:check -P client-cpp -P site -P code-coverage
      - name: Test Server Module with Maven
        run:  mvn -B clean post-integration-test -Dtest.port.closed=true -Pcode-coverage
      - name: Code Coverage (Coveralls)
        if: ${{ success() && matrix.os == 'ubuntu-latest' && matrix.java == '11.0.x'}}
        run: |
          mvn -B post-integration-test -Pcode-coverage -pl code-coverage
          mvn -B coveralls:report \
          -DserviceName=travis_ci \
          -Dbranch=$BRANCH_NAME \
          -DpullRequest=$PR_NUMBER \
          -DrepoToken=MiEOlMMMNQhLNV4yayn7rRUPyVSQzbzbZ \
          -Pcode-coverage
      - name: SonarCloud Report
        if: ${{ success() && matrix.os == 'ubuntu-latest' && matrix.java == '11.0.x'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: '2d9c9a58d772a57806a168e00181e3e19f2763dc'
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.organization=apache \
          -Dsonar.projectKey=apache_incubator-iotdb \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} \
          -DskipTests -pl '!distribution' -am
