# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run-Tests-for-Sonar-Coveralls

on:
  push:
    branches:
      - master
      - "rel/*"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - master
      - "rel/*"
      - cluster_new
    paths-ignore:
      - "docs/**"

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      #- name: IT/UT Test
        # we do not compile client-cpp for saving time, it is tested in client.yml
      #  run: mvn -B clean post-integration-test -Dtest.port.closed=true -Pcode-coverage
